/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SparseMerkleTree {
  export type ProofStruct = {
    root: BytesLike;
    siblings: BytesLike[];
    existence: boolean;
    key: BytesLike;
    value: BytesLike;
    auxExistence: boolean;
    auxKey: BytesLike;
    auxValue: BytesLike;
  };

  export type ProofStructOutput = [
    root: string,
    siblings: string[],
    existence: boolean,
    key: string,
    value: string,
    auxExistence: boolean,
    auxKey: string,
    auxValue: string,
  ] & {
    root: string;
    siblings: string[];
    existence: boolean;
    key: string;
    value: string;
    auxExistence: boolean;
    auxKey: string;
    auxValue: string;
  };
}

export declare namespace VerifierHelper {
  export type ProofPointsStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
  };

  export type ProofPointsStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
  };
}

export interface SmtCheckerInterface extends Interface {
  getFunction(nameOrSignature: "addElement" | "getProof" | "getRoot" | "verifier" | "verifyProof"): FunctionFragment;

  encodeFunctionData(functionFragment: "addElement", values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getProof", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "getRoot", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifyProof", values: [BigNumberish, VerifierHelper.ProofPointsStruct]): string;

  decodeFunctionResult(functionFragment: "addElement", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getProof", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyProof", data: BytesLike): Result;
}

export interface SmtChecker extends BaseContract {
  connect(runner?: ContractRunner | null): SmtChecker;
  waitForDeployment(): Promise<this>;

  interface: SmtCheckerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  addElement: TypedContractMethod<[index_: BigNumberish, elem_: BigNumberish], [void], "nonpayable">;

  getProof: TypedContractMethod<[index_: BigNumberish], [SparseMerkleTree.ProofStructOutput], "view">;

  getRoot: TypedContractMethod<[], [bigint], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyProof: TypedContractMethod<[root_: BigNumberish, points_: VerifierHelper.ProofPointsStruct], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "addElement",
  ): TypedContractMethod<[index_: BigNumberish, elem_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProof",
  ): TypedContractMethod<[index_: BigNumberish], [SparseMerkleTree.ProofStructOutput], "view">;
  getFunction(nameOrSignature: "getRoot"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "verifier"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyProof",
  ): TypedContractMethod<[root_: BigNumberish, points_: VerifierHelper.ProofPointsStruct], [boolean], "view">;

  filters: {};
}
