name: setup

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16.18.x"
        cache: npm
    - name: Install packages
      run: npm install
      shell: bash
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Download and locate circom binary
        run: |
          curl --location --request GET https://github.com/iden3/circom/releases/latest/download/circom-linux-amd64 --output $HOME/.cargo/bin/circom
          chmod +x $HOME/.cargo/bin/circom