/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  PoseidonUnit4L,
  PoseidonUnit4LInterface,
} from "../../../../../@iden3/contracts/lib/Poseidon.sol/PoseidonUnit4L";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[4]",
        name: "",
        type: "uint256[4]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610120610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063248f6677146038575b600080fd5b604e6004803603810190604a91906092565b6062565b6040516059919060d1565b60405180910390f35b6000919050565b600080fd5b600080fd5b600081905082602060040282011115608c57608b606e565b5b92915050565b60006080828403121560a55760a46069565b5b600060b1848285016073565b91505092915050565b6000819050919050565b60cb8160ba565b82525050565b600060208201905060e4600083018460c4565b9291505056fea26469706673582212202284b271f331d5ea9699873fdf06f904eb1ebd22f80f2ffe03cd65b90fcd633064736f6c63430008100033";

type PoseidonUnit4LConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (xs: PoseidonUnit4LConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
  xs.length > 1;

export class PoseidonUnit4L__factory extends ContractFactory {
  constructor(...args: PoseidonUnit4LConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PoseidonUnit4L & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PoseidonUnit4L__factory {
    return super.connect(runner) as PoseidonUnit4L__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit4LInterface {
    return new Interface(_abi) as PoseidonUnit4LInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PoseidonUnit4L {
    return new Contract(address, _abi, runner) as unknown as PoseidonUnit4L;
  }
}
