name: "checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
      - feat/github-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Compile
        env:
          NODE_OPTIONS: "--max_old_space_size=15999"
        run: npm run compile
      - name: Run tests
        run: npm run test
